### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luametalatex#1]
I am under macOS darwin, 
- installed ConTeXt in /opt/ConTeXt, 
- copied luametatex into /usr/local/texlive/bin/x86_64-darwin/
- installed luametalatex in /usr/local/src
- run ./install.sh
- updated the FNDB
- and tried to create the formats:
```

bash-3.2$ ./install.sh 
LUAINPUTS for luametalatex already set. In case of issues, please verify that the entries are correct.
luametalatex format already known. In case of issues, please verify that the entries are correct.
INSTALLED
bash-3.2$ fmtutil-sys --byfmt luametalatex
fmtutil: fmtutil is using the following fmtutil.cnf files (in precedence order):
fmtutil:   /usr/local/texlive/texmf-local/web2c/fmtutil.cnf
fmtutil:   /usr/local/texlive/texmf-dist/web2c/fmtutil.cnf
fmtutil: fmtutil is using the following fmtutil.cnf file for writing changes:
fmtutil:   /usr/local/texlive/texmf-config/web2c/fmtutil.cnf
fmtutil [INFO]: writing formats under /usr/local/texlive/texmf-var/web2c
fmtutil [INFO]: --- remaking luametalatex with luametatex
fmtutil: running `luametatex -ini   -jobname=luametalatex -progname=luametalatex --lua="$(kpsewhich luametalatex.lua)" luametalatex.ini' ...
lua error : function call: /usr/local/src/luametalatex/luametalatex-init.lua:11: C support library not found. Please fix your installation
open(luametalatex.log) failed, not copying: No such file or directory at /usr/local/texlive/tlpkg/TeXLive/TLUtils.pm line 1269.
fmtutil [ERROR]: running `luametatex -ini   -jobname=luametalatex -progname=luametalatex --lua="$(kpsewhich luametalatex.lua)" luametalatex.ini </dev/null' return status: 1
fmtutil [ERROR]: failed to copy log luametalatex.log to: /usr/local/texlive/texmf-var/web2c/luametatex
fmtutil [ERROR]: returning error due to option --strict
fmtutil [INFO]: disabled formats: 5
fmtutil [INFO]: not selected formats: 56
fmtutil [INFO]: failed to build: 1 (luametatex/luametalatex)
fmtutil [INFO]: total formats: 62
fmtutil [INFO]: exiting with status 1
```

**Comment by zauguin** [comment]
Sorry, I totally missed this issue.

The problem is that LuaMetaLaTeX for compatibility with traditional LuaLaTeX depends on kpathsea. Since that isn't supported by default in LuaMetaTeX, LuaMetaLaTeX ships with a shared library providing the traditional kpathsea Lua wrapper from LuaTeX with some additions. Currently this is only provided for Linux x86-64 and Windows (for the simple reason that these are the only systems I can easily compile stuff for).

If you don't mind compiling this yourself I can send you the source and Makefile if you are still interested.

**Comment by hvoss49** [comment]
Yes, please send me the source.

**Comment by zauguin** [comment]
It's on https://git.math.hamburg/marcel/luametalatex-c
Read the Makefile for minimal build instructions. (They were not really meant to be read by anyone beside me, to they are mostly small notes) The hard part are the dependencies: It does not only contain kpathsea but also HarfBuzz for full compatibility, so it requires a prebuild HarfBuzz, Graphite (only if Graphite is enabled in HarfBuzz), TeX Live (or at least kpathsea) and Lua (current development version) buildtree, each of them build as static libraries but with shared library build options.

**Comment by hvoss49** [comment]
Thanks, I'll see what I can do ...
