### ISSUE TITLE
`\formatname` and `tex.formatname` are empty

### ISSUE THREAD

**Issue by gucci-on-fleek** [zauguin/luametalatex#6]
`\formatname` and `tex.formatname` are always empty. Example:

```tex
\message{\formatname}
\directlua{print(tex.formatname)}
\end
```

According to the LuaMetaTeX manual, both of these commands have been removed from the engine, but that doesn't actually seem to be the case since `\formatname` is defined but empty and `tex.formatname` is an empty string instead of `nil`. 

Both `\formatname` and `tex.formatname` work in ConTeXt LMTX, although I couldn't figure out how they're set.

**Comment by zauguin** [comment]
It's a question of engine versions. `formatname` works again in the updated LuaMetaTeX version, but that version breaks accent placement in LaTeX, so updating requires a bit more thought.

**Comment by zauguin** [comment]
Hopefully fixed, but requires an updated engine (so rerunning the installer).

**Comment by gucci-on-fleek** [comment]
Yep, it's fixed. Thanks!
